config/routes.rb
Rails.application.routes.draw do
  resources :splash, only: [:index]
  resources :entities, only: %i[:index new create destroy] do
    resources :relations, only: [:create]
  end
  resources :groups, only: %i[index show new create destroy]
  
  devise_for :users
   root to: 'groups#index'
    get '/users/sign_out' => 'devise/sessions#destroy'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def index
    @entity = entities.all
  end

  def new
    @relation = Relation.new(entity: @entity)
    @entity = current_user.entities.new
  end

  def create
    @entity = current_user.entities.new(entity_params)
    respond_to do |format|
      format.html do
        if @entity.save
          @relation = Relation.create(group_id: group_params, entity_id: @entity.id)
          flash[:notice] = 'New Entity was successfully created'
          redirect_to group_path(@relation.group_id)
        else
          render :new
        end
      end
    end
  end

  def destroy
    @entity = current_user.entities.find(params[:id]).destroy
    flash[:notice] = 'Entity was successfully deleted'
    redirect_to groups_path
  end

  private

  def group_params
    params[:entity][:relation][:group_id]
  end

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ActionController::Base
  def index
    @groups = current_user.groups.all
  end

  def new
    @group = current_user.groups.new
  end

  def show
    @group = Group.find(params[:id])
    @relations = @group.relations.order('created_at DESC')
  end

  def create
    @group = current_user.groups.new(group_params)
    respond_to do |format|
      format.html do
        if @group.save
          redirect_to groups_path
          flash[:notice] = 'New Group was successfully created'
        else
          render :new
        end
      end
    end
  end

  def destroy
    @group = current_user.groups.find(params[:id]).destroy
    flash[:notice] = 'Group was successfully deleted'
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  def index
    @relation = Relation.new
    @entity = current_user.entities.new
    @group = Group.all
  end

  def new
    @relation = Relation.new
    @entity = current_user.entities.new
    @group = Group.all
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/entities/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
  </head>

  <body>
    
    <div class="body">
      <div class="box form">
        <h1 class = "new-entity-header">Add A New Transaction</h1>

        <%= form_with model: @entity do |form| %>

          <div class="entity-name mb-3">
            <%= form.label :name %>
            <%= form.text_field :name, required: true, class: "name-field form-control"%>
          </div>

          <div class="entity-amount mb-3">
              <%= form.label :amount %>
              <%= form.number_field :amount, required: true, min: 1, class: "amount-field form-control"%>
          </div>
        
          <div class="entity-quantity mb-3">
            <%= form.fields_for(@relation) do |relation| %>
              <%= relation.label :group%>
              <%= relation.select :group_id, current_user.groups.collect { |group| [group.name, group.id]}, {include_blank: true}, required: true, class: "form-control"%>
            <% end %>   
          </div>

          <div class="mb-3">
            <%= form.submit class: "submit-btn submit-entity-btn" %>
          </div>

        <%end%>
      </div>
    </div>


  </body>
</html>

app/views/groups/index.html.erb
<%= render "partials/nav" %>

<div class="main group-container">

  <%@groups.each do |group|%>
  
    <div class="category-details-container category ">

      <img class= "category-image" src=<%=group.icon%> alt="category-icon">

      <div class="flex">
        <%= link_to group_path(group.id), :remote => true do %>
          <h2 class = "category-name">
            <%=group.name%>
          </h2>
        <%end%>

        <h6>
          <%=group.created_at%>
        </h6>
      </div>

      <div class="flex category-total">
        <h3 class = group-total>
          $<%=group.self_total(group.id)%>
        </h3>
        <%= button_to "Delete", group_path(group.id), html: {'data-turbo' => "false"}, :method => :delete, class: "btn btn-danger group-delete-btn" %>
      </div>

    </div>

  <%end%>
  
  <%= link_to new_group_path, :remote => true do %>
    <input type="button" class="category-btn btn  last" value="Add New Category">
  <% end %>

</div>

app/views/groups/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csp_meta_tag %>
    <%= csrf_meta_tags %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    
    <div class="form-container body">
      <div class="box">

        <h1 class="new-category-header">Add A New Category</h1>

        <%= form_with model: @group do |form| %>
              
          <div class="form-name-container mb-3">
              <%= form.label :name %> :
              <%= form.text_field :name, required: true, class: "form-name form-control"%>
          </div>

          <div class="form-icon-container mb-3">
              <%= form.label :icon %> :
              <%= form.text_field :icon, required: true, class: "form-icon form-control"%>
          </div>

          <div class="submit-btn-container mb-3">
              <%= form.submit "Create New Category", class: "submit-btn create-category-btn" %>
          </div>
              
        <% end %>

        <%= link_to '/', :remote => true do %>
          <input type="button" class="back-btn category-back-btn" value="Go Back">
        <% end %>

      </div>
    </div>
  </body>
</html>

app/views/groups/show.html.erb
<%= render "partials/navbar" %>
<div class="credit">
  <h2>Gift Credit</h2>
  <h3 class= "entity-total">$<%=@group.self_total(@group.id)%>.00</h3>
</div>

<div class="main">

  <%@relations.each do |r|%>
  
    <%entity = Entity.find(r.entity_id)%>
    <div class="category container">
      <img class="category-img"src=<%=@group.icon%> alt="category-icon">
      
      <div class="entity-name-container flex">
        <h3 class = "entity-name"><%=entity.name%></h3>
        <h3 class = "entity-creation-date"> <%=entity.created_at%></h3>
      </div>

      <div class="flex">
        <h3 class = "entity-amount">$<%=entity.amount%>.00</h3>
        <%= button_to "Delete", entity_path(entity.id), html: {'data-turbo' => "false"}, :method => :delete, class: "delete-btn btn btn-danger" %>
      </div>
    </div>

  <%end%>

  <div class="buton-container flex1">

    <%= link_to new_entity_path, :remote => true do %>
      <input type="button" class="add-btn btn btn-primary" value="Add New transaction">
    <% end %>

    <%= link_to groups_path, :remote => true do %>
      <input type="button" class="back-btn btn btn-primary" value="Go Back">
    <% end %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csp_meta_tag %>
    <%= csrf_meta_tags %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    
    <nav class="navbar navbar-expand-lg">
      
      <%= link_to groups_path, :remote => true do %>
        <i class="fa fa-lg fa-arrow-left" style="color:white"></i>
      <%end%>

      <a class="transaction-link navbar-brand" href="/groups">Transactions</a>
   
      <%= link_to destroy_user_session_path, method: :get do %>
        <i class="fa fa-lg fa-sign-out" style="color:white" ></i>
      <% end %>
   
   </nav>
   
  </body>
</html>

app/views/partials/_navbar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <nav class="navbar navbar-expand-lg">

      <i class="fa fa-arrow-left fa-lg" style="color:white"></i>

      <a class="navbar-brand" href="/groups">Categories</a>
   
      <%= link_to destroy_user_session_path, method: :get do %>
        <i class="fa fa-sign-out fa-lg" style="color:white" ></i>
      <% end %>
   
   </nav>

  </body>
</html>

app/views/relations/new.html.erb
<h1>Relations#new</h1>
<p>This is the relations Page</p>

app/views/splash/index.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= csp_meta_tag %>
    <%= csrf_meta_tags %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>

    <section class="home-section body">

      <div class="box homepage-container">

        <h1 class = "welcome-message"> Budget App</h1>
        <%= link_to new_user_registration_path, :class => 'navbar-link', :remote => true do  %>
          <input type="button" class="sign-up-btn" value="SIGN UP">
        <%end%>

        <%= link_to new_user_session_path, :class => 'navbar-link', :remote => true do  %>
          <input type="button" class="log-in-btn" value="LOG IN">
        <%end%>
      </div>

    </section>
    
  </body>
</html>